# Generated by Django 5.0.3 on 2024-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='support',
            name='division_assigned_to',
            field=models.TextField(blank=True, db_column='Division Assigned To', null=True),
        ),
    ]
