# Generated by Django 5.0.3 on 2024-05-20 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_support_division_assigned_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rms',
            fields=[
                ('sr_no', models.TextField(db_column='Sr No', primary_key=True, serialize=False)),
                ('ticket_number', models.TextField(blank=True, db_column='Ticket Number', null=True)),
                ('date', models.TextField(blank=True, db_column='Date', null=True)),
                ('broking_id', models.TextField(blank=True, db_column='Broking ID', null=True)),
                ('name', models.TextField(blank=True, db_column='Name', null=True)),
                ('contact_number', models.TextField(blank=True, db_column='Contact Number', null=True)),
                ('email_id', models.TextField(blank=True, db_column='Email ID', null=True)),
                ('customer_type', models.TextField(blank=True, db_column='Customer Type', null=True)),
                ('priority', models.TextField(blank=True, db_column='Priority', null=True)),
                ('issue', models.TextField(blank=True, db_column='Issue', null=True)),
                ('comment', models.TextField(blank=True, db_column='Comment', null=True)),
                ('assigned_to', models.TextField(blank=True, db_column='Assigned To', null=True)),
                ('status', models.TextField(blank=True, db_column='Status', null=True)),
                ('date_of_closing', models.TextField(blank=True, db_column='Date of Closing', null=True)),
                ('rms_status', models.TextField(blank=True, db_column='RMS Status', null=True)),
                ('rms_comment', models.TextField(blank=True, db_column='RMS Comment', null=True)),
                ('broker', models.ForeignKey(blank=True, db_column='Broker', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.broker')),
                ('employee', models.ForeignKey(blank=True, db_column='Employee', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.algobullsemployee')),
            ],
            options={
                'db_table': 'Rms',
                'managed': True,
            },
        ),
    ]
