# Generated by Django 5.0.3 on 2024-05-26 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rms'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='entry_date',
            field=models.TextField(blank=True, db_column='Entry Date', null=True),
        ),
    ]
