# Generated by Django 5.0.3 on 2024-06-04 06:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_sales_entry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branchemployee',
            name='role',
            field=models.ForeignKey(blank=True, db_column='Role', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='base.authrole'),
        ),
    ]
