# Generated by Django 5.0.3 on 2024-06-24 18:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='authpermission',
            name='employee_type',
            field=models.CharField(choices=[('Algobulls Employee', 'Algobulls Employee'), ('Branch Employee', 'Branch Employee')], default='Algobulls Employee', max_length=50),
        ),
        migrations.AddField(
            model_name='authpermission',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
