# Generated by Django 5.0.3 on 2024-06-25 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_authpermission_employee_type_authpermission_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='authpermission',
            name='employee_type',
            field=models.CharField(blank=True, choices=[('Algobulls Employee', 'Algobulls Employee'), ('Branch Employee', 'Branch Employee')], default='Algobulls Employee', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='authpermission',
            name='user',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
