# Generated by Django 5.0.3 on 2024-06-25 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_authpermission_employee_type_and_more'),
    ]

    
