# Generated by Django 5.0.3 on 2024-06-26 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_authpermission_id_alter_authpermission_permission_id'),
    ]

    operations = [
        
    ]
