# Generated by Django 5.0.3 on 2024-06-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_alter_authpermission_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authpermission',
            old_name='permission_id',
            new_name='id',
        ),
    ]
