# Generated by Django 5.0.3 on 2024-06-26 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_rename_permission_id_authpermission_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authpermission',
            old_name='id',
            new_name='permission_id',
        ),
    ]
